server:
  port: "8080"
  mode: "debug"

database:
  host: "localhost"
  port: "5433"
  user: "wwvpn"
  password: "wwvpn"
  name: "wwvpn"
  sslmode: "disable"

redis:
  host: "localhost"
  port: "6380"
  password: ""
  db: 0

jwt:
  secret: "change-me-jwt-secret-32-chars!!"
  ttl: 10080

admin:
  api_key: "wwvpn-admin-secret-key-change-me"
