// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/servers": {
            "get": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all servers (admin)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/dto.AdminServerResponse"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Add VPN server (admin)",
                "parameters": [
                    {
                        "description": "Server details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.AddServerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/servers/{id}": {
            "delete": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Remove VPN server (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/servers/{id}/active": {
            "put": {
                "security": [
                    {
                        "AdminKey": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Set server active/inactive (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Server UUID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Active status",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.SetActiveRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/account": {
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Delete account",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/device": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Authenticate device",
                "parameters": [
                    {
                        "description": "Device ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DeviceAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/connect": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connect"
                ],
                "summary": "Connect to VPN server",
                "parameters": [
                    {
                        "description": "Connection params",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ConnectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ConnectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/connect/disconnect": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "connect"
                ],
                "summary": "Disconnect from VPN server",
                "parameters": [
                    {
                        "description": "Connection ID",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.DisconnectRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/servers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "servers"
                ],
                "summary": "List active VPN servers",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.ServerListResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/subscription/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Get subscription status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/webhook/revenuecat": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "RevenueCat webhook",
                "responses": {
                    "501": {
                        "description": "Not Implemented",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AddServerRequest": {
            "type": "object",
            "required": [
                "awg_port",
                "awg_public_key",
                "city",
                "country",
                "grpc_port",
                "hostname",
                "ip_address",
                "vless_port",
                "vless_public_key",
                "vless_short_id"
            ],
            "properties": {
                "awg_port": {
                    "type": "integer"
                },
                "awg_public_key": {
                    "type": "string"
                },
                "camouflage_domain": {
                    "type": "string"
                },
                "capacity": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "grpc_port": {
                    "type": "integer"
                },
                "hostname": {
                    "type": "string"
                },
                "ip_address": {
                    "type": "string"
                },
                "is_premium": {
                    "type": "boolean"
                },
                "vless_port": {
                    "type": "integer"
                },
                "vless_public_key": {
                    "type": "string"
                },
                "vless_short_id": {
                    "type": "string"
                }
            }
        },
        "dto.AdminServerResponse": {
            "type": "object",
            "properties": {
                "active_connections": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ip_address": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_premium": {
                    "type": "boolean"
                }
            }
        },
        "dto.AuthResponse": {
            "type": "object",
            "properties": {
                "device_id": {
                    "type": "string"
                },
                "expire_at": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "dto.ConnectRequest": {
            "type": "object",
            "required": [
                "client_public_key",
                "protocol",
                "server_id"
            ],
            "properties": {
                "client_public_key": {
                    "type": "string"
                },
                "protocol": {
                    "type": "string",
                    "enum": [
                        "amnezia_wg",
                        "vless_reality",
                        "auto"
                    ]
                },
                "server_id": {
                    "type": "string"
                }
            }
        },
        "dto.ConnectResponse": {
            "type": "object",
            "properties": {
                "allowed_ips": {
                    "type": "string"
                },
                "assigned_ip": {
                    "type": "string"
                },
                "connection_id": {
                    "type": "string"
                },
                "dns": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "fallback": {
                    "$ref": "#/definitions/dto.FallbackConfig"
                },
                "mtu": {
                    "type": "integer"
                },
                "obfuscation": {
                    "$ref": "#/definitions/dto.ObfuscationParams"
                },
                "protocol": {
                    "type": "string"
                },
                "server_public_key": {
                    "type": "string"
                },
                "vless": {
                    "$ref": "#/definitions/dto.VLESSParams"
                }
            }
        },
        "dto.DeviceAuthRequest": {
            "type": "object",
            "required": [
                "device_id"
            ],
            "properties": {
                "device_id": {
                    "type": "string"
                }
            }
        },
        "dto.DisconnectRequest": {
            "type": "object",
            "required": [
                "connection_id"
            ],
            "properties": {
                "connection_id": {
                    "type": "string"
                }
            }
        },
        "dto.FallbackConfig": {
            "type": "object",
            "properties": {
                "assigned_ip": {
                    "type": "string"
                },
                "connection_id": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "obfuscation": {
                    "$ref": "#/definitions/dto.ObfuscationParams"
                },
                "protocol": {
                    "type": "string"
                },
                "server_public_key": {
                    "type": "string"
                },
                "vless": {
                    "$ref": "#/definitions/dto.VLESSParams"
                }
            }
        },
        "dto.ObfuscationParams": {
            "type": "object",
            "properties": {
                "h1": {
                    "type": "integer"
                },
                "h2": {
                    "type": "integer"
                },
                "h3": {
                    "type": "integer"
                },
                "h4": {
                    "type": "integer"
                },
                "jc": {
                    "type": "integer"
                },
                "jmax": {
                    "type": "integer"
                },
                "jmin": {
                    "type": "integer"
                },
                "s1": {
                    "type": "integer"
                },
                "s2": {
                    "type": "integer"
                }
            }
        },
        "dto.ServerListResponse": {
            "type": "object",
            "properties": {
                "servers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.ServerResponse"
                    }
                }
            }
        },
        "dto.ServerResponse": {
            "type": "object",
            "properties": {
                "capacity": {
                    "type": "integer"
                },
                "city": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_premium": {
                    "type": "boolean"
                },
                "load": {
                    "type": "integer"
                },
                "protocols": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.SetActiveRequest": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                }
            }
        },
        "dto.VLESSParams": {
            "type": "object",
            "properties": {
                "port": {
                    "type": "integer"
                },
                "public_key": {
                    "type": "string"
                },
                "short_id": {
                    "type": "string"
                },
                "sni": {
                    "type": "string"
                },
                "uuid": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "AdminKey": {
            "type": "apiKey",
            "name": "X-Admin-Key",
            "in": "header"
        },
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "wwvpn API",
	Description:      "VPN backend API with AmneziaWG and VLESS+Reality protocols",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
