// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/node.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPeerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Protocol        string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ClientPublicKey string                 `protobuf:"bytes,2,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"`
	DeviceUuid      string                 `protobuf:"bytes,3,opt,name=device_uuid,json=deviceUuid,proto3" json:"device_uuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddPeerRequest) Reset() {
	*x = AddPeerRequest{}
	mi := &file_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeerRequest) ProtoMessage() {}

func (x *AddPeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeerRequest.ProtoReflect.Descriptor instead.
func (*AddPeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

func (x *AddPeerRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AddPeerRequest) GetClientPublicKey() string {
	if x != nil {
		return x.ClientPublicKey
	}
	return ""
}

func (x *AddPeerRequest) GetDeviceUuid() string {
	if x != nil {
		return x.DeviceUuid
	}
	return ""
}

type AddPeerResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerPublicKey string                 `protobuf:"bytes,1,opt,name=server_public_key,json=serverPublicKey,proto3" json:"server_public_key,omitempty"`
	Endpoint        string                 `protobuf:"bytes,2,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	AllowedIps      string                 `protobuf:"bytes,3,opt,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Dns             string                 `protobuf:"bytes,4,opt,name=dns,proto3" json:"dns,omitempty"`
	AssignedIp      string                 `protobuf:"bytes,5,opt,name=assigned_ip,json=assignedIp,proto3" json:"assigned_ip,omitempty"`
	Jc              int32                  `protobuf:"varint,6,opt,name=jc,proto3" json:"jc,omitempty"`
	Jmin            int32                  `protobuf:"varint,7,opt,name=jmin,proto3" json:"jmin,omitempty"`
	Jmax            int32                  `protobuf:"varint,8,opt,name=jmax,proto3" json:"jmax,omitempty"`
	S1              int32                  `protobuf:"varint,9,opt,name=s1,proto3" json:"s1,omitempty"`
	S2              int32                  `protobuf:"varint,10,opt,name=s2,proto3" json:"s2,omitempty"`
	H1              int32                  `protobuf:"varint,11,opt,name=h1,proto3" json:"h1,omitempty"`
	H2              int32                  `protobuf:"varint,12,opt,name=h2,proto3" json:"h2,omitempty"`
	H3              int32                  `protobuf:"varint,13,opt,name=h3,proto3" json:"h3,omitempty"`
	H4              int32                  `protobuf:"varint,14,opt,name=h4,proto3" json:"h4,omitempty"`
	VlessUuid       string                 `protobuf:"bytes,15,opt,name=vless_uuid,json=vlessUuid,proto3" json:"vless_uuid,omitempty"`
	VlessPublicKey  string                 `protobuf:"bytes,16,opt,name=vless_public_key,json=vlessPublicKey,proto3" json:"vless_public_key,omitempty"`
	VlessShortId    string                 `protobuf:"bytes,17,opt,name=vless_short_id,json=vlessShortId,proto3" json:"vless_short_id,omitempty"`
	VlessSni        string                 `protobuf:"bytes,18,opt,name=vless_sni,json=vlessSni,proto3" json:"vless_sni,omitempty"`
	VlessPort       int32                  `protobuf:"varint,19,opt,name=vless_port,json=vlessPort,proto3" json:"vless_port,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AddPeerResponse) Reset() {
	*x = AddPeerResponse{}
	mi := &file_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPeerResponse) ProtoMessage() {}

func (x *AddPeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPeerResponse.ProtoReflect.Descriptor instead.
func (*AddPeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *AddPeerResponse) GetServerPublicKey() string {
	if x != nil {
		return x.ServerPublicKey
	}
	return ""
}

func (x *AddPeerResponse) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AddPeerResponse) GetAllowedIps() string {
	if x != nil {
		return x.AllowedIps
	}
	return ""
}

func (x *AddPeerResponse) GetDns() string {
	if x != nil {
		return x.Dns
	}
	return ""
}

func (x *AddPeerResponse) GetAssignedIp() string {
	if x != nil {
		return x.AssignedIp
	}
	return ""
}

func (x *AddPeerResponse) GetJc() int32 {
	if x != nil {
		return x.Jc
	}
	return 0
}

func (x *AddPeerResponse) GetJmin() int32 {
	if x != nil {
		return x.Jmin
	}
	return 0
}

func (x *AddPeerResponse) GetJmax() int32 {
	if x != nil {
		return x.Jmax
	}
	return 0
}

func (x *AddPeerResponse) GetS1() int32 {
	if x != nil {
		return x.S1
	}
	return 0
}

func (x *AddPeerResponse) GetS2() int32 {
	if x != nil {
		return x.S2
	}
	return 0
}

func (x *AddPeerResponse) GetH1() int32 {
	if x != nil {
		return x.H1
	}
	return 0
}

func (x *AddPeerResponse) GetH2() int32 {
	if x != nil {
		return x.H2
	}
	return 0
}

func (x *AddPeerResponse) GetH3() int32 {
	if x != nil {
		return x.H3
	}
	return 0
}

func (x *AddPeerResponse) GetH4() int32 {
	if x != nil {
		return x.H4
	}
	return 0
}

func (x *AddPeerResponse) GetVlessUuid() string {
	if x != nil {
		return x.VlessUuid
	}
	return ""
}

func (x *AddPeerResponse) GetVlessPublicKey() string {
	if x != nil {
		return x.VlessPublicKey
	}
	return ""
}

func (x *AddPeerResponse) GetVlessShortId() string {
	if x != nil {
		return x.VlessShortId
	}
	return ""
}

func (x *AddPeerResponse) GetVlessSni() string {
	if x != nil {
		return x.VlessSni
	}
	return ""
}

func (x *AddPeerResponse) GetVlessPort() int32 {
	if x != nil {
		return x.VlessPort
	}
	return 0
}

type RemovePeerRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Protocol        string                 `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	ClientPublicKey string                 `protobuf:"bytes,2,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"`
	VlessUuid       string                 `protobuf:"bytes,3,opt,name=vless_uuid,json=vlessUuid,proto3" json:"vless_uuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RemovePeerRequest) Reset() {
	*x = RemovePeerRequest{}
	mi := &file_proto_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerRequest) ProtoMessage() {}

func (x *RemovePeerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerRequest.ProtoReflect.Descriptor instead.
func (*RemovePeerRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{2}
}

func (x *RemovePeerRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RemovePeerRequest) GetClientPublicKey() string {
	if x != nil {
		return x.ClientPublicKey
	}
	return ""
}

func (x *RemovePeerRequest) GetVlessUuid() string {
	if x != nil {
		return x.VlessUuid
	}
	return ""
}

type RemovePeerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePeerResponse) Reset() {
	*x = RemovePeerResponse{}
	mi := &file_proto_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePeerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePeerResponse) ProtoMessage() {}

func (x *RemovePeerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePeerResponse.ProtoReflect.Descriptor instead.
func (*RemovePeerResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{3}
}

func (x *RemovePeerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListPeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersRequest) Reset() {
	*x = ListPeersRequest{}
	mi := &file_proto_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersRequest) ProtoMessage() {}

func (x *ListPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersRequest.ProtoReflect.Descriptor instead.
func (*ListPeersRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{4}
}

type ListPeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveCount   int32                  `protobuf:"varint,1,opt,name=active_count,json=activeCount,proto3" json:"active_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPeersResponse) Reset() {
	*x = ListPeersResponse{}
	mi := &file_proto_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPeersResponse) ProtoMessage() {}

func (x *ListPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPeersResponse.ProtoReflect.Descriptor instead.
func (*ListPeersResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{5}
}

func (x *ListPeersResponse) GetActiveCount() int32 {
	if x != nil {
		return x.ActiveCount
	}
	return 0
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_proto_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_proto_node_proto protoreflect.FileDescriptor

const file_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x10proto/node.proto\x12\x04node\"y\n" +
	"\x0eAddPeerRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12*\n" +
	"\x11client_public_key\x18\x02 \x01(\tR\x0fclientPublicKey\x12\x1f\n" +
	"\vdevice_uuid\x18\x03 \x01(\tR\n" +
	"deviceUuid\"\xf0\x03\n" +
	"\x0fAddPeerResponse\x12*\n" +
	"\x11server_public_key\x18\x01 \x01(\tR\x0fserverPublicKey\x12\x1a\n" +
	"\bendpoint\x18\x02 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vallowed_ips\x18\x03 \x01(\tR\n" +
	"allowedIps\x12\x10\n" +
	"\x03dns\x18\x04 \x01(\tR\x03dns\x12\x1f\n" +
	"\vassigned_ip\x18\x05 \x01(\tR\n" +
	"assignedIp\x12\x0e\n" +
	"\x02jc\x18\x06 \x01(\x05R\x02jc\x12\x12\n" +
	"\x04jmin\x18\a \x01(\x05R\x04jmin\x12\x12\n" +
	"\x04jmax\x18\b \x01(\x05R\x04jmax\x12\x0e\n" +
	"\x02s1\x18\t \x01(\x05R\x02s1\x12\x0e\n" +
	"\x02s2\x18\n" +
	" \x01(\x05R\x02s2\x12\x0e\n" +
	"\x02h1\x18\v \x01(\x05R\x02h1\x12\x0e\n" +
	"\x02h2\x18\f \x01(\x05R\x02h2\x12\x0e\n" +
	"\x02h3\x18\r \x01(\x05R\x02h3\x12\x0e\n" +
	"\x02h4\x18\x0e \x01(\x05R\x02h4\x12\x1d\n" +
	"\n" +
	"vless_uuid\x18\x0f \x01(\tR\tvlessUuid\x12(\n" +
	"\x10vless_public_key\x18\x10 \x01(\tR\x0evlessPublicKey\x12$\n" +
	"\x0evless_short_id\x18\x11 \x01(\tR\fvlessShortId\x12\x1b\n" +
	"\tvless_sni\x18\x12 \x01(\tR\bvlessSni\x12\x1d\n" +
	"\n" +
	"vless_port\x18\x13 \x01(\x05R\tvlessPort\"z\n" +
	"\x11RemovePeerRequest\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\tR\bprotocol\x12*\n" +
	"\x11client_public_key\x18\x02 \x01(\tR\x0fclientPublicKey\x12\x1d\n" +
	"\n" +
	"vless_uuid\x18\x03 \x01(\tR\tvlessUuid\".\n" +
	"\x12RemovePeerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x12\n" +
	"\x10ListPeersRequest\"6\n" +
	"\x11ListPeersResponse\x12!\n" +
	"\factive_count\x18\x01 \x01(\x05R\vactiveCount\"\x0f\n" +
	"\rHealthRequest\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion2\xfc\x01\n" +
	"\tNodeAgent\x126\n" +
	"\aAddPeer\x12\x14.node.AddPeerRequest\x1a\x15.node.AddPeerResponse\x12?\n" +
	"\n" +
	"RemovePeer\x12\x17.node.RemovePeerRequest\x1a\x18.node.RemovePeerResponse\x12<\n" +
	"\tListPeers\x12\x16.node.ListPeersRequest\x1a\x17.node.ListPeersResponse\x128\n" +
	"\vHealthCheck\x12\x13.node.HealthRequest\x1a\x14.node.HealthResponseB)Z'github.com/wwvpn/wwvpn/internal/node/pbb\x06proto3"

var (
	file_proto_node_proto_rawDescOnce sync.Once
	file_proto_node_proto_rawDescData []byte
)

func file_proto_node_proto_rawDescGZIP() []byte {
	file_proto_node_proto_rawDescOnce.Do(func() {
		file_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)))
	})
	return file_proto_node_proto_rawDescData
}

var file_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_node_proto_goTypes = []any{
	(*AddPeerRequest)(nil),     // 0: node.AddPeerRequest
	(*AddPeerResponse)(nil),    // 1: node.AddPeerResponse
	(*RemovePeerRequest)(nil),  // 2: node.RemovePeerRequest
	(*RemovePeerResponse)(nil), // 3: node.RemovePeerResponse
	(*ListPeersRequest)(nil),   // 4: node.ListPeersRequest
	(*ListPeersResponse)(nil),  // 5: node.ListPeersResponse
	(*HealthRequest)(nil),      // 6: node.HealthRequest
	(*HealthResponse)(nil),     // 7: node.HealthResponse
}
var file_proto_node_proto_depIdxs = []int32{
	0, // 0: node.NodeAgent.AddPeer:input_type -> node.AddPeerRequest
	2, // 1: node.NodeAgent.RemovePeer:input_type -> node.RemovePeerRequest
	4, // 2: node.NodeAgent.ListPeers:input_type -> node.ListPeersRequest
	6, // 3: node.NodeAgent.HealthCheck:input_type -> node.HealthRequest
	1, // 4: node.NodeAgent.AddPeer:output_type -> node.AddPeerResponse
	3, // 5: node.NodeAgent.RemovePeer:output_type -> node.RemovePeerResponse
	5, // 6: node.NodeAgent.ListPeers:output_type -> node.ListPeersResponse
	7, // 7: node.NodeAgent.HealthCheck:output_type -> node.HealthResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_node_proto_init() }
func file_proto_node_proto_init() {
	if File_proto_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_proto_goTypes,
		DependencyIndexes: file_proto_node_proto_depIdxs,
		MessageInfos:      file_proto_node_proto_msgTypes,
	}.Build()
	File_proto_node_proto = out.File
	file_proto_node_proto_goTypes = nil
	file_proto_node_proto_depIdxs = nil
}
